BucketList/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'

  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :list_items
end

BucketList/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BucketList/app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :user

  validates_presence_of :name, :description
end

BucketList/app/models/user.rb
class User < ApplicationRecord
  PASSWORD_LENGTH = (4..25)
  USERNAME_LENGTH = (4..15)

  validates_presence_of :username
  validates_presence_of :password_digest
  validates :username, length: USERNAME_LENGTH, uniqueness: true

  validates :password, length: PASSWORD_LENGTH, allow_nil: true

  has_many :list_items

  attr_reader :password

  def self.find_from_credentials(username, password)
    user = find_by(username: username)
    return nil unless user
    user if user.is_password?(password)
  end

  def is_password?(password_attempt)
    BCrypt::Password.new(password_digest).is_password?(password_attempt)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

end

BucketList/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def sign_in(user)
    session[:session_token] = SecureRandom.urlsafe_base64
    user.update!(session_token: session[:session_token])
  end

  def sign_out
    return unless current_user
    current_user.update!(session_token: nil)
    session.delete(:session_token)
  end

  def current_user
    @current_user ||= find_current_user
  end

  def find_current_user
    session_token = session[:session_token]
    session_token && User.find_by(session_token: session_token)
  end

  def ensure_signed_in
    return if current_user
    flash[:error] = 'you must be signed in to see this'
    redirect_to :root
  end

  def ensure_signed_out
    return unless current_user
    flash[:error] = 'you are already signed in'
    redirect_to users_path
  end
end

BucketList/app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController

  before_action :ensure_signed_in
  before_action :load_list_item, only: [:show, :edit, :update, :destroy]

  def new
    @item = ListItem.new
  end

  def create
    @item = ListItem.new(create_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = 'Bucket item created!'
      redirect_to list_item_path(@item)
    else
      flash[:error] = @item.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(update_params)
      flash[:notice] = 'Item updated!'
      redirect_to list_item_path(@item)
    else
      flash[:error] = @item.errors.full_messages.join(', ')
      render :edit
    end
  end

  def index
    @items = current_user.list_items
  end

  def show
  end

  def destroy
    @list_item.destroy!

    flash[:notice] = "#{@list_item.name} deleted!"
    redirect_to list_items_path
  end

  private

  def create_params
    params.require(:list_item).permit(:name, :description)
  end

  def update_params
    params.require(:list_item).permit(:description)
  end

  def load_list_item
    @item = current_user.list_items.find(params[:id])
  end
end

BucketList/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :ensure_signed_out, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    username = user_params[:username]
    password = user_params[:password]

    user = User.find_from_credentials(username, password)

    if user
      sign_in(user)
      flash[:notice] = "Hi, #{username}! You signed in!"
      redirect_to users_path
    else
      flash[:error] = "User not found :("
      @user = User.new(username: username)
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = 'You signed out!'
    redirect_to new_session_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

BucketList/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_signed_out, only: [:new, :create]
  before_action :ensure_signed_in, only: [:show, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)

    if @user.save
      sign_in(@user)
      flash[:notice] = 'You are signed in!'
      redirect_to users_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def create_params
    params.require(:user).permit(:username, :password)
  end
end

BucketList/app/helpers/application_helper.rb
module ApplicationHelper
end

BucketList/app/helpers/list_items_helper.rb
module ListItemsHelper
end

BucketList/app/helpers/sessions_helper.rb
module SessionsHelper
end

BucketList/app/helpers/users_helper.rb
module UsersHelper
end

BucketList/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">Bucket List</div>

    <% if current_user %>
      <br><br>
      <%= link_to 'Users', users_path %>
      |
      <%= link_to 'Bucket List', list_items_path %>
      |
      <%= link_to 'Create Item', new_list_item_path %>
    <% end %>

    <br><br>

    <% if current_user %>
      <%= link_to current_user.username, user_path(current_user) %> signed in
      <%= button_to 'Log out', session_path, method: :delete %>
    <% end %>

    <% if flash[:notice].present? %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:error].present? %>
      <div class="errors">
        <b>Errors:</b>

        <%= flash[:error] %>
      </div>
    <% end %>

    <%= yield %>

    <div class="footer"></div>
  </body>
</html>

BucketList/app/views/list_items/edit.html.erb
<h2>Update List</h2>

<%= form_for @item do |form| %>

  <%= label_tag :name %>

  <b><%= @item.name %></b>
  <br>
  <%= label_tag :description %>
  <br>
  <%= form.text_area :description, placeholder: 'Description' %>

  <br>
  <%= submit_tag 'Update list!' %>
<% end %>

BucketList/app/views/list_items/index.html.erb
<h2>Bucket List</h2>

<% if @items.empty? %>
  No items

<% else %>
  <ul>
    <% @items.each do |item| %>
      <li><%= link_to item.name, list_item_path(item) %></li>
    <% end %>
  </ul>
<% end %>

BucketList/app/views/list_items/new.html.erb
<h2>Create a new item</h2>

<%= form_for @item do |form| %>
  <%= form.text_field :name, placeholder: 'Name' %>
  <br>
  <%= form.text_area :description, placeholder: 'Description' %>

  <br>
  <%= submit_tag 'Create item!' %>
<% end %>

BucketList/app/views/list_items/show.html.erb
<h2><%= @item.name %></h2>

Description:
<p><i><%= @item.description %></i></p>
<br>
<%= button_to 'Delete item', list_item_path(@item), method: :delete %>
<br>
<%= link_to 'Edit item', edit_list_item_path(@item) %>
<br>

BucketList/app/views/users/index.html.erb
<h3>Users</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user) %></li>
  <% end %>
</ul>

BucketList/app/views/users/new.html.erb
<h2> Create an account </h2>

<%= form_for @user do |form| %>
  <%= form.text_field :username,
        placeholder: 'Username',
        required: true,
        minlength: User::USERNAME_LENGTH.begin,
        maxlength: User::USERNAME_LENGTH.end
  %>

  <%= form.password_field :password,
        placeholder: 'password',
        required: true,
        minlength: User::PASSWORD_LENGTH.begin,
        maxlength: User::PASSWORD_LENGTH.end
  %>

  <%= submit_tag 'Create Account!' %>
<% end %>

<br>
Returning user? <%= link_to 'Sign in', new_session_path %>

BucketList/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

blah blah blah more info on this user

<br>

<%= link_to 'all users', users_path %>